-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.alembic_version
(
    version_num character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

CREATE TABLE IF NOT EXISTS public.app_state
(
    key text COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT app_state_pkey PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS public.book_subscriptions
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    book_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT book_subscriptions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_book_sub UNIQUE (user_id, book_id)
);

CREATE TABLE IF NOT EXISTS public.book_tags
(
    id serial NOT NULL,
    book_id integer NOT NULL,
    tag_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    is_spoiler integer NOT NULL DEFAULT 0,
    CONSTRAINT book_tags_pkey PRIMARY KEY (id),
    CONSTRAINT uq_book_tag UNIQUE (book_id, tag_id)
);

CREATE TABLE IF NOT EXISTS public.bookmarks
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    book_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    reading_status character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'reading'::character varying,
    CONSTRAINT bookmarks_pkey PRIMARY KEY (id),
    CONSTRAINT uq_bookmark_user_book UNIQUE (user_id, book_id)
);

CREATE TABLE IF NOT EXISTS public.books
(
    id serial NOT NULL,
    title character varying(300) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(350) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    cover_emoji character varying(10) COLLATE pg_catalog."default" NOT NULL,
    cover_url character varying(500) COLLATE pg_catalog."default",
    author_id integer NOT NULL,
    genre genre NOT NULL,
    status bookstatus NOT NULL,
    views_count integer NOT NULL,
    likes_count integer NOT NULL,
    bookmarks_count integer NOT NULL,
    chapters_count integer NOT NULL,
    words_count integer NOT NULL,
    reviews_count integer NOT NULL,
    rating double precision NOT NULL,
    is_published boolean NOT NULL,
    is_adult boolean NOT NULL,
    is_featured boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    direction character varying(20) COLLATE pg_catalog."default" DEFAULT 'gen'::character varying,
    is_draft_hidden boolean NOT NULL DEFAULT false,
    is_on_moderation boolean NOT NULL DEFAULT false,
    content_warnings character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT books_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chapters
(
    id serial NOT NULL,
    book_id integer NOT NULL,
    "number" integer NOT NULL,
    title character varying(300) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default",
    words_count integer NOT NULL,
    views_count integer NOT NULL,
    is_published boolean NOT NULL,
    author_note text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    is_draft_hidden boolean NOT NULL DEFAULT false,
    CONSTRAINT chapters_pkey PRIMARY KEY (id),
    CONSTRAINT uq_chapter_book_num UNIQUE (book_id, "number")
);

CREATE TABLE IF NOT EXISTS public.follows
(
    id serial NOT NULL,
    follower_id integer NOT NULL,
    following_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT follows_pkey PRIMARY KEY (id),
    CONSTRAINT uq_follow UNIQUE (follower_id, following_id)
);

CREATE TABLE IF NOT EXISTS public.likes
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    book_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT likes_pkey PRIMARY KEY (id),
    CONSTRAINT uq_like_user_book UNIQUE (user_id, book_id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    kind character varying(50) COLLATE pg_catalog."default" NOT NULL,
    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    body character varying(500) COLLATE pg_catalog."default",
    link character varying(500) COLLATE pg_catalog."default",
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.oauth_accounts
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    provider character varying(50) COLLATE pg_catalog."default" NOT NULL,
    provider_user_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    access_token character varying(1000) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT oauth_accounts_pkey PRIMARY KEY (id),
    CONSTRAINT uq_oauth_provider_uid UNIQUE (provider, provider_user_id)
);

CREATE TABLE IF NOT EXISTS public.reading_progress
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    book_id integer NOT NULL,
    chapter_id integer,
    percent integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT reading_progress_pkey PRIMARY KEY (id),
    CONSTRAINT uq_progress_user_book UNIQUE (user_id, book_id)
);

CREATE TABLE IF NOT EXISTS public.refresh_tokens
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    token_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked boolean NOT NULL,
    user_agent character varying(300) COLLATE pg_catalog."default",
    ip_address character varying(50) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.reports
(
    id serial NOT NULL,
    reporter_id integer NOT NULL,
    book_id integer NOT NULL,
    reason character varying(100) COLLATE pg_catalog."default" NOT NULL,
    comment character varying(500) COLLATE pg_catalog."default",
    is_resolved boolean NOT NULL DEFAULT false,
    resolved_by integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT reports_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.reviews
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    book_id integer NOT NULL,
    rating double precision NOT NULL,
    text text COLLATE pg_catalog."default",
    is_hidden boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    is_spoiler boolean NOT NULL DEFAULT false,
    helpful_count integer NOT NULL DEFAULT 0,
    CONSTRAINT reviews_pkey PRIMARY KEY (id),
    CONSTRAINT uq_review_user_book UNIQUE (user_id, book_id)
);

CREATE TABLE IF NOT EXISTS public.tags
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(60) COLLATE pg_catalog."default" NOT NULL,
    usage_count integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT tags_pkey PRIMARY KEY (id),
    CONSTRAINT tags_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    hashed_password character varying(255) COLLATE pg_catalog."default",
    display_name character varying(100) COLLATE pg_catalog."default",
    bio text COLLATE pg_catalog."default",
    avatar_url character varying(500) COLLATE pg_catalog."default",
    role userrole NOT NULL,
    is_active boolean NOT NULL,
    is_verified boolean NOT NULL,
    is_banned boolean NOT NULL,
    ban_reason character varying(500) COLLATE pg_catalog."default",
    followers_count integer NOT NULL,
    following_count integer NOT NULL,
    works_count integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    website character varying(255) COLLATE pg_catalog."default",
    oauth_provider character varying(50) COLLATE pg_catalog."default",
    oauth_provider_id character varying(255) COLLATE pg_catalog."default",
    last_login timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.book_subscriptions
    ADD CONSTRAINT book_subscriptions_book_id_fkey FOREIGN KEY (book_id)
    REFERENCES public.books (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_book_subscriptions_book_id
    ON public.book_subscriptions(book_id);


ALTER TABLE IF EXISTS public.book_subscriptions
    ADD CONSTRAINT book_subscriptions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_book_subscriptions_user_id
    ON public.book_subscriptions(user_id);


ALTER TABLE IF EXISTS public.book_tags
    ADD CONSTRAINT book_tags_book_id_fkey FOREIGN KEY (book_id)
    REFERENCES public.books (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_book_tags_book_id
    ON public.book_tags(book_id);


ALTER TABLE IF EXISTS public.book_tags
    ADD CONSTRAINT book_tags_tag_id_fkey FOREIGN KEY (tag_id)
    REFERENCES public.tags (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_book_tags_tag_id
    ON public.book_tags(tag_id);


ALTER TABLE IF EXISTS public.bookmarks
    ADD CONSTRAINT bookmarks_book_id_fkey FOREIGN KEY (book_id)
    REFERENCES public.books (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_bookmarks_book_id
    ON public.bookmarks(book_id);


ALTER TABLE IF EXISTS public.bookmarks
    ADD CONSTRAINT bookmarks_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_bookmarks_user_id
    ON public.bookmarks(user_id);


ALTER TABLE IF EXISTS public.books
    ADD CONSTRAINT books_author_id_fkey FOREIGN KEY (author_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_books_author_id
    ON public.books(author_id);


ALTER TABLE IF EXISTS public.chapters
    ADD CONSTRAINT chapters_book_id_fkey FOREIGN KEY (book_id)
    REFERENCES public.books (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_chapters_book_id
    ON public.chapters(book_id);


ALTER TABLE IF EXISTS public.follows
    ADD CONSTRAINT follows_follower_id_fkey FOREIGN KEY (follower_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_follows_follower_id
    ON public.follows(follower_id);


ALTER TABLE IF EXISTS public.follows
    ADD CONSTRAINT follows_following_id_fkey FOREIGN KEY (following_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_follows_following_id
    ON public.follows(following_id);


ALTER TABLE IF EXISTS public.likes
    ADD CONSTRAINT likes_book_id_fkey FOREIGN KEY (book_id)
    REFERENCES public.books (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_likes_book_id
    ON public.likes(book_id);


ALTER TABLE IF EXISTS public.likes
    ADD CONSTRAINT likes_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_likes_user_id
    ON public.likes(user_id);


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_notifications_user_id
    ON public.notifications(user_id);


ALTER TABLE IF EXISTS public.oauth_accounts
    ADD CONSTRAINT oauth_accounts_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_oauth_accounts_user_id
    ON public.oauth_accounts(user_id);


ALTER TABLE IF EXISTS public.reading_progress
    ADD CONSTRAINT reading_progress_book_id_fkey FOREIGN KEY (book_id)
    REFERENCES public.books (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_reading_progress_book_id
    ON public.reading_progress(book_id);


ALTER TABLE IF EXISTS public.reading_progress
    ADD CONSTRAINT reading_progress_chapter_id_fkey FOREIGN KEY (chapter_id)
    REFERENCES public.chapters (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.reading_progress
    ADD CONSTRAINT reading_progress_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_reading_progress_user_id
    ON public.reading_progress(user_id);


ALTER TABLE IF EXISTS public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user_id
    ON public.refresh_tokens(user_id);


ALTER TABLE IF EXISTS public.reports
    ADD CONSTRAINT reports_book_id_fkey FOREIGN KEY (book_id)
    REFERENCES public.books (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_reports_book_id
    ON public.reports(book_id);


ALTER TABLE IF EXISTS public.reports
    ADD CONSTRAINT reports_reporter_id_fkey FOREIGN KEY (reporter_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_reports_reporter_id
    ON public.reports(reporter_id);


ALTER TABLE IF EXISTS public.reports
    ADD CONSTRAINT reports_resolved_by_fkey FOREIGN KEY (resolved_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_book_id_fkey FOREIGN KEY (book_id)
    REFERENCES public.books (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_reviews_book_id
    ON public.reviews(book_id);


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_reviews_user_id
    ON public.reviews(user_id);

END;